### ISSUE TITLE
Question - Does it work when the Delphi IDE is running?

### ISSUE THREAD

**Issue by edwinyzh** [littleearth/delphi-library-helper#1]
Does the program work when the Delphi IDE is running? I mean, when the IDE is running,  does it recognize changes in the helper immediately ? Or will the settings made by the two conflicts with each other? 

Thanks.

**Comment by littleearth** [comment]
It is better to have Delphi closed. You can apply changes with DLH then open Delphi option and click ok. That seems to work.
