### ISSUE TITLE
compiler error on delphi 10.2.1 Tokyo

### ISSUE THREAD

**Issue by tintinsoft** [littleearth/delphi-library-helper#2]
procedure TMaybeObjectWrapperType<T>.Cleanup(var AValue: T);
begin
  { Only free if it's an object! }
  if (FAllowCleanup) and (TypeInfo <> nil) and (TypeInfo^.Kind = tkClass) then
    FreeAndNil(TObject(AValue));
end;

[dcc32 Error] DeHL.Types.pas(5168): E2089 Invalid typecast

**Comment by littleearth** [comment]
Latest build compiles with Delphi Tokyo 10.2.1
