### ISSUE TITLE
Browse path

### ISSUE THREAD

**Issue by jkour** [littleearth/delphi-library-helper#5]
An option for the browsing paths would be useful.

Thanks

**Comment by littleearth** [comment]
Could you please clarify; if you double click an entry you can browse, there are also right mouse click menu options such as browse / copy

**Comment by jkour** [comment]
Sorry, I mean that now the editor manages the entries in Library>Search Paths.

It would be nice to be able to manage the Library>Browse Paths

**Comment by littleearth** [comment]
This feature is now available

**Comment by jkour** [comment]
In the repo, you don't have an exe file.

I need the Jedi library to build it on my PC.

**Comment by littleearth** [comment]
you can download it here http://www.littleearthsolutions.net/?page_id=99

**Comment by jkour** [comment]
Great thanks
